package dev.awd.whistle.utils

object Constants {
    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
    const val ACTION_SERVICE_STOP = "ACTION_SERVICE_STOP"
    const val ACTION_SERVICE_RESET = "ACTION_SERVICE_RESET"
    const val ACTION_SERVICE_LAP = "ACTION_SERVICE_LAP"

    const val NOTIFICATION_CHANNEL_ID = "WHISTLE_NOTIFICATION_ID"
    const val NOTIFICATION_CHANNEL_NAME = "WHISTLE_NOTIFICATION"
    const val NOTIFICATION_ID = 10

    const val CLICK_REQUEST_CODE = 100
    const val RESET_REQUEST_CODE = 101
    const val STOP_REQUEST_CODE = 102
    const val RESUME_REQUEST_CODE = 103
}